"use client";

import * as React from "react";
import * as LabelPrimitive from "@radix-ui/react-label";
import { Slot } from "@radix-ui/react-slot";
import {
  Controller,
  ControllerProps,
  FieldPath,
  FieldValues,
  FormProvider,
  useFormContext,
} from "react-hook-form";

import { cn } from "@/lib/utils";
import { Label } from "@/components/ui/label";

const Form = FormProvider;

/**
 * This file is autogenerated by Shadcn. It contains the Form component
 * which is a wrapper around react-hook-form's FormProvider.
 * It provides a way to manage form state and validation.
 *
 * @file components/ui/form.tsx
 * @author Son Nguyen
 * @license MIT
 * @version 1.0.0
 * @date 2025-05-11
 */

/**
 * FormFieldContextValue type to define the context value for form fields.
 * This type includes the name of the field and its state.
 *
 * @template TFieldValues - The type of field values.
 * @template TName - The type of field name.
 */
type FormFieldContextValue<
  TFieldValues extends FieldValues = FieldValues,
  TName extends FieldPath<TFieldValues> = FieldPath<TFieldValues>,
> = {
  name: TName;
};

/**
 * FormFieldContext to provide context for form fields.
 * This context includes the name of the field and its state.
 *
 * @template TFieldValues - The type of field values.
 * @template TName - The type of field name.
 */
const FormFieldContext = React.createContext<FormFieldContextValue>(
  {} as FormFieldContextValue,
);

/**
 * FormField component using react-hook-form's Controller.
 * This component provides a way to manage form fields and their state.
 *
 * @param {ControllerProps} props - The props for the Controller component.
 * @returns {JSX.Element} The FormField component.
 */
const FormField = <
  TFieldValues extends FieldValues = FieldValues,
  TName extends FieldPath<TFieldValues> = FieldPath<TFieldValues>,
>({
  ...props
}: ControllerProps<TFieldValues, TName>) => {
  return (
    <FormFieldContext.Provider value={{ name: props.name }}>
      <Controller {...props} />
    </FormFieldContext.Provider>
  );
};

/**
 * useFormField hook to access the form field context.
 * This hook provides access to the field state and other properties.
 *
 * @returns {object} The form field properties.
 */
const useFormField = () => {
  const fieldContext = React.useContext(FormFieldContext);
  const itemContext = React.useContext(FormItemContext);
  const { getFieldState, formState } = useFormContext();

  const fieldState = getFieldState(fieldContext.name, formState);

  if (!fieldContext) {
    throw new Error("useFormField should be used within <FormField>");
  }

  const { id } = itemContext;

  return {
    id,
    name: fieldContext.name,
    formItemId: `${id}-form-item`,
    formDescriptionId: `${id}-form-item-description`,
    formMessageId: `${id}-form-item-message`,
    ...fieldState,
  };
};

/**
 * FormItemContextValue type to define the context value for form items.
 * This type includes the id of the form item.
 *
 * @template TFieldValues - The type of field values.
 * @template TName - The type of field name.
 */
type FormItemContextValue = {
  id: string;
};

/**
 * FormItemContext to provide context for form items.
 * This context includes the id of the form item.
 *
 * @template TFieldValues - The type of field values.
 * @template TName - The type of field name.
 */
const FormItemContext = React.createContext<FormItemContextValue>(
  {} as FormItemContextValue,
);

/**
 * FormItem component to wrap form fields and provide context.
 * This component provides a way to manage form items and their state.
 *
 * @param {React.HTMLAttributes<HTMLDivElement>} props - The props for the FormItem component.
 * @returns {JSX.Element} The FormItem component.
 */
const FormItem = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => {
  const id = React.useId();

  return (
    <FormItemContext.Provider value={{ id }}>
      <div ref={ref} className={cn("space-y-2", className)} {...props} />
    </FormItemContext.Provider>
  );
});
FormItem.displayName = "FormItem";

/**
 * FormLabel component using Radix UI's LabelPrimitive.
 * This component provides a label for form fields.
 *
 * @param {React.ComponentPropsWithoutRef<typeof LabelPrimitive.Root>} props - The props for the FormLabel component.
 * @returns {JSX.Element} The FormLabel component.
 */
const FormLabel = React.forwardRef<
  React.ElementRef<typeof LabelPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof LabelPrimitive.Root>
>(({ className, ...props }, ref) => {
  const { error, formItemId } = useFormField();

  return (
    <Label
      ref={ref}
      className={cn(error && "text-destructive", className)}
      htmlFor={formItemId}
      {...props}
    />
  );
});
FormLabel.displayName = "FormLabel";

/**
 * FormControl component using Radix UI's Slot.
 * This component provides a way to manage form controls and their state.
 *
 * @param {React.ComponentPropsWithoutRef<typeof Slot>} props - The props for the FormControl component.
 * @returns {JSX.Element} The FormControl component.
 */
const FormControl = React.forwardRef<
  React.ElementRef<typeof Slot>,
  React.ComponentPropsWithoutRef<typeof Slot>
>(({ ...props }, ref) => {
  const { error, formItemId, formDescriptionId, formMessageId } =
    useFormField();

  return (
    <Slot
      ref={ref}
      id={formItemId}
      aria-describedby={
        !error
          ? `${formDescriptionId}`
          : `${formDescriptionId} ${formMessageId}`
      }
      aria-invalid={!!error}
      {...props}
    />
  );
});
FormControl.displayName = "FormControl";

/**
 * FormDescription component to provide additional information about the form field.
 * This component provides a way to manage form descriptions and their state.
 *
 * @param {React.HTMLAttributes<HTMLParagraphElement>} props - The props for the FormDescription component.
 * @returns {JSX.Element} The FormDescription component.
 */
const FormDescription = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLParagraphElement>
>(({ className, ...props }, ref) => {
  const { formDescriptionId } = useFormField();

  return (
    <p
      ref={ref}
      id={formDescriptionId}
      className={cn("text-sm text-muted-foreground", className)}
      {...props}
    />
  );
});
FormDescription.displayName = "FormDescription";

/**
 * FormMessage component to display error messages for form fields.
 * This component provides a way to manage form messages and their state.
 *
 * @param {React.HTMLAttributes<HTMLParagraphElement>} props - The props for the FormMessage component.
 * @returns {JSX.Element} The FormMessage component.
 */
const FormMessage = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLParagraphElement>
>(({ className, children, ...props }, ref) => {
  const { error, formMessageId } = useFormField();
  const body = error ? String(error?.message) : children;

  if (!body) {
    return null;
  }

  return (
    <p
      ref={ref}
      id={formMessageId}
      className={cn("text-sm font-medium text-destructive", className)}
      {...props}
    >
      {body}
    </p>
  );
});
FormMessage.displayName = "FormMessage";

export {
  useFormField,
  Form,
  FormItem,
  FormLabel,
  FormControl,
  FormDescription,
  FormMessage,
  FormField,
};
