import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

/**
 * This file is autogenerated by Shadcn. It contains utility functions
 * for handling class names and merging Tailwind CSS classes.
 *
 * @file lib/utils.ts
 * @author Son Nguyen
 * @license MIT
 * @version 1.0.0
 * @date 2025-05-11
 */

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
